function phase2medical = Medical_DM_data_import_phase_2_medical(dataLines)
%IMPORTFILE Import data from a text file
%  PHASE2MEDICAL = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  PHASE2MEDICAL = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  phase2medical = importfile("\Medical_DM_data\phase2_medical.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Aug-2024 20:37:02

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 50);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "Med_Risk_25_SI_R", "Med_Risk_50_ModI_R", "Med_Ambig_24_ModI_R", "Med_Ambig_74_ModI_R", "Med_Risk_75_MajI_R", "Med_Ambig_50_MajI_R", "Med_Ambig_100_MajI_G", "Med_Risk_75_R_R", "Med_Ambig_50_SI_B", "Med_Risk_50_ModI_B", "Med_Ambig_50_MajI_B", "Med_Ambig_100_MajI_G1", "Med_Risk_25_R_B", "Med_Ambig_100_SI_G", "Med_Risk_25_MajI_R", "Med_Ambig_24_MajI_R", "Med_Risk_25_R_R", "Med_Risk_50_SI_B", "Med_Risk_75_ModI_B", "Med_Ambig_24_ModI_B", "Med_Risk_50_MajI_B", "Med_Risk_75_R_B", "Med_Ambig_50_R_B", "Med_Ambig_74_R_B", "Med_Ambig_74_SI_R", "Med_Risk_25_ModI_R", "Med_Ambig_50_ModI_R", "Med_Ambig_100_ModI_G", "Med_Risk_50_MajI_R", "Med_Risk_50_R_R", "Med_Ambig_50_R_R", "Med_Ambig_74_R_R", "Med_Ambig_50_ModI_B", "Med_Risk_25_MajI_B", "Med_Risk_75_MajI_B", "Med_Ambig_24_MajI_B", "Med_Ambig_74_MajI_B", "Med_Ambig_100_R_G", "Med_Risk_75_SI_R", "Med_Risk_75_ModI_R", "Med_Ambig_74_MajI_R", "Med_Ambig_24_R_R", "Med_Ambig_100_R_G1", "Med_Ambig_24_SI_B", "Med_Risk_25_ModI_B", "Med_Ambig_74_ModI_B", "Med_Ambig_100_ModI_G1", "Med_Risk_50_R_B", "Med_Ambig_24_R_R1"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
phase2medical = readtable("Medical_DM_data\phase2_medical.csv", opts);

end