function phase1medical = Medical_DM_data_import_phase_1_medical()
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: \Medical_DM_data\phase1_medical.csv
%
% Auto-generated by MATLAB on 05-Aug-2024 20:35:05

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 50);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "Med_Risk_25_SI_R", "Med_Risk_50_ModI_R", "Med_Ambig_24_ModI_R", "Med_Ambig_74_ModI_R", "Med_Risk_75_MajI_R", "Med_Ambig_50_MajI_R", "Med_Ambig_100_MajI_G", "Med_Risk_75_R_R", "Med_Ambig_50_SI_B", "Med_Risk_50_ModI_B", "Med_Ambig_50_MajI_B", "Med_Ambig_100_MajI_G1", "Med_Risk_25_R_B", "Med_Ambig_100_SI_G", "Med_Risk_25_MajI_R", "Med_Ambig_24_MajI_R", "Med_Risk_25_R_R", "Med_Risk_50_SI_B", "Med_Risk_75_ModI_B", "Med_Ambig_24_ModI_B", "Med_Risk_50_MajI_B", "Med_Risk_75_R_B", "Med_Ambig_50_R_B", "Med_Ambig_74_R_B", "Med_Ambig_74_SI_R", "Med_Risk_25_ModI_R", "Med_Ambig_50_ModI_R", "Med_Ambig_100_ModI_G", "Med_Risk_50_MajI_R", "Med_Risk_50_R_R", "Med_Ambig_50_R_R", "Med_Ambig_74_R_R", "Med_Ambig_50_ModI_B", "Med_Risk_25_MajI_B", "Med_Risk_75_MajI_B", "Med_Ambig_24_MajI_B", "Med_Ambig_74_MajI_B", "Med_Ambig_100_R_G", "Med_Risk_75_SI_R", "Med_Risk_75_ModI_R", "Med_Ambig_74_MajI_R", "Med_Ambig_24_R_R", "Med_Ambig_100_R_G1", "Med_Ambig_24_SI_B", "Med_Risk_25_ModI_B", "Med_Ambig_74_ModI_B", "Med_Ambig_100_ModI_G1", "Med_Risk_50_R_B", "Med_Ambig_24_R_R1"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
phase1medical = readtable("Medical_DM_data\phase1_medical.csv", opts);


%% Clear temporary variables
clear opts
end